Remove and reclone repo if URL has changed.
iridl/iridl-ansible pull request #4
Opened 2022-08-11 16:18 UTC by aaron-kaplan

...plus some fixes to unrelated problems I noticed while working on it. Please read commit-by-commit.

This can wait until after PR #3. I'll rebase and resolve conflicts if necessary.

2022-08-31 20:47 UTC, aaron-kaplan commented
@kgraaf

2022-08-31 20:55 UTC, kgraaf requested changes

2022-08-31 20:55 UTC, kgraaf commented on roles/iridl/templates/update_datalib
> +            echo $repo
remove printf debugging

2022-08-31 20:57 UTC, kgraaf commented
make sure this doesn't semantically conflict with master, since the update_script has been reordered since this PR was created

2022-09-01 01:38 UTC, aaron-kaplan commented
@kgraaf I've removed the debugging prints, rebased, and retested.

2022-09-01 19:33 UTC, kgraaf approved these changes

2022-09-01 19:33 UTC, merged